/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mcf_fa_tools;

/**
 *
 * @author 7162859
 */
public class VersionHistory extends javax.swing.JFrame {

  /**
   * Creates new form VersionHistory
   */
  public VersionHistory() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHistoryLog = new javax.swing.JTextArea();
        LabelVersionNum = new javax.swing.JLabel();
        jLabelFeatureList = new javax.swing.JLabel();
        isGetRawData_Support = new javax.swing.JCheckBox();
        isExecuteBench_Support = new javax.swing.JCheckBox();
        isGetSCCCOM_Support = new javax.swing.JCheckBox();
        isCheckHDDHistory_Support = new javax.swing.JCheckBox();
        isReportBenchResult_Support = new javax.swing.JCheckBox();
        isGetWrapperLog_Support = new javax.swing.JCheckBox();
        isGetFAInfo_support = new javax.swing.JCheckBox();
        isSolutionGuildline_Support = new javax.swing.JCheckBox();
        isAlertOnline_Support = new javax.swing.JCheckBox();
        isReserved1 = new javax.swing.JCheckBox();
        isReserved2 = new javax.swing.JCheckBox();
        isReserved3 = new javax.swing.JCheckBox();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MCF FA tools version: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MCF FA tools version: ");

        jTextAreaHistoryLog.setBackground(new java.awt.Color(255, 255, 204));
        jTextAreaHistoryLog.setColumns(20);
        jTextAreaHistoryLog.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jTextAreaHistoryLog.setRows(5);
        jTextAreaHistoryLog.setText("\n                             History  \n\n|    Date     | Version | Comment\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n| 25/Aug/2018 |    00.02| Initial Feature support list\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n| 24/Aug/2018 |    00.01| InitialGUI\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n\n\n\nEND of history");
        jTextAreaHistoryLog.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaHistoryLog);

        LabelVersionNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelVersionNum.setForeground(new java.awt.Color(0, 153, 51));
        LabelVersionNum.setText("00.02");

        jLabelFeatureList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFeatureList.setText("Feature support:");

        isGetRawData_Support.setText("Get Rawdata");
        isGetRawData_Support.setEnabled(false);

        isExecuteBench_Support.setText("Execute bench test");
        isExecuteBench_Support.setEnabled(false);
        isExecuteBench_Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isExecuteBench_SupportActionPerformed(evt);
            }
        });

        isGetSCCCOM_Support.setText("Get SCC-COM log");
        isGetSCCCOM_Support.setEnabled(false);
        isGetSCCCOM_Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isGetSCCCOM_SupportActionPerformed(evt);
            }
        });

        isCheckHDDHistory_Support.setText("Check drive history");
        isCheckHDDHistory_Support.setEnabled(false);
        isCheckHDDHistory_Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isCheckHDDHistory_SupportActionPerformed(evt);
            }
        });

        isReportBenchResult_Support.setText("Report Bench result");
        isReportBenchResult_Support.setEnabled(false);
        isReportBenchResult_Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isReportBenchResult_SupportActionPerformed(evt);
            }
        });

        isGetWrapperLog_Support.setText("Get Wrapper log");
        isGetWrapperLog_Support.setEnabled(false);
        isGetWrapperLog_Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isGetWrapperLog_SupportActionPerformed(evt);
            }
        });

        isGetFAInfo_support.setText("Get FA info");
        isGetFAInfo_support.setEnabled(false);
        isGetFAInfo_support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isGetFAInfo_supportActionPerformed(evt);
            }
        });

        isSolutionGuildline_Support.setText("Provide solution guildline");
        isSolutionGuildline_Support.setEnabled(false);
        isSolutionGuildline_Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSolutionGuildline_SupportActionPerformed(evt);
            }
        });

        isAlertOnline_Support.setText("Alert online");
        isAlertOnline_Support.setEnabled(false);
        isAlertOnline_Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAlertOnline_SupportActionPerformed(evt);
            }
        });

        isReserved1.setText("reserved1");
        isReserved1.setEnabled(false);
        isReserved1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isReserved1ActionPerformed(evt);
            }
        });

        isReserved2.setText("reserved2");
        isReserved2.setEnabled(false);
        isReserved2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isReserved2ActionPerformed(evt);
            }
        });

        isReserved3.setText("reserved3");
        isReserved3.setEnabled(false);
        isReserved3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isReserved3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelVersionNum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFeatureList))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isGetRawData_Support, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isGetWrapperLog_Support, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isGetSCCCOM_Support))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isCheckHDDHistory_Support)
                            .addComponent(isExecuteBench_Support)
                            .addComponent(isReportBenchResult_Support))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isGetFAInfo_support)
                            .addComponent(isSolutionGuildline_Support)
                            .addComponent(isAlertOnline_Support))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isReserved1)
                            .addComponent(isReserved2)
                            .addComponent(isReserved3))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelVersionNum))
                .addGap(30, 30, 30)
                .addComponent(jLabelFeatureList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(isReserved1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isReserved2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isReserved3)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(isCheckHDDHistory_Support)
                                    .addComponent(isGetRawData_Support))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(isExecuteBench_Support)
                                    .addComponent(isGetWrapperLog_Support))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(isReportBenchResult_Support)
                                    .addComponent(isGetSCCCOM_Support)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isGetFAInfo_support)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isSolutionGuildline_Support)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isAlertOnline_Support)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
  
  }//GEN-LAST:event_formWindowClosed

    private void isExecuteBench_SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isExecuteBench_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isExecuteBench_SupportActionPerformed

    private void isGetSCCCOM_SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isGetSCCCOM_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isGetSCCCOM_SupportActionPerformed

    private void isReportBenchResult_SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isReportBenchResult_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isReportBenchResult_SupportActionPerformed

    private void isGetWrapperLog_SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isGetWrapperLog_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isGetWrapperLog_SupportActionPerformed

    private void isCheckHDDHistory_SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isCheckHDDHistory_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isCheckHDDHistory_SupportActionPerformed

    private void isGetFAInfo_supportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isGetFAInfo_supportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isGetFAInfo_supportActionPerformed

    private void isSolutionGuildline_SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSolutionGuildline_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isSolutionGuildline_SupportActionPerformed

    private void isAlertOnline_SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAlertOnline_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isAlertOnline_SupportActionPerformed

    private void isReserved1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isReserved1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isReserved1ActionPerformed

    private void isReserved2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isReserved2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isReserved2ActionPerformed

    private void isReserved3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isReserved3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isReserved3ActionPerformed

  /**
   * @param args the command line arguments
   */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelVersionNum;
    private javax.swing.JCheckBox isAlertOnline_Support;
    private javax.swing.JCheckBox isCheckHDDHistory_Support;
    private javax.swing.JCheckBox isExecuteBench_Support;
    private javax.swing.JCheckBox isGetFAInfo_support;
    private javax.swing.JCheckBox isGetRawData_Support;
    private javax.swing.JCheckBox isGetSCCCOM_Support;
    private javax.swing.JCheckBox isGetWrapperLog_Support;
    private javax.swing.JCheckBox isReportBenchResult_Support;
    private javax.swing.JCheckBox isReserved1;
    private javax.swing.JCheckBox isReserved2;
    private javax.swing.JCheckBox isReserved3;
    private javax.swing.JCheckBox isSolutionGuildline_Support;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFeatureList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaHistoryLog;
    // End of variables declaration//GEN-END:variables
}
